//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYGIS.Livelihood
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HYMSDTEntities : DbContext
    {
        public HYMSDTEntities()
            : base("name=HYMSDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_BusLine> T_BusLine { get; set; }
        public virtual DbSet<T_BusLine_Station> T_BusLine_Station { get; set; }
        public virtual DbSet<T_Culture> T_Culture { get; set; }
        public virtual DbSet<T_Culture_Community> T_Culture_Community { get; set; }
        public virtual DbSet<T_Health> T_Health { get; set; }
        public virtual DbSet<T_LeisureTourism> T_LeisureTourism { get; set; }
        public virtual DbSet<T_Service> T_Service { get; set; }
        public virtual DbSet<T_Station> T_Station { get; set; }
        public virtual DbSet<T_Traffic> T_Traffic { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
        public virtual DbSet<海盐> 海盐 { get; set; }
    }
}
