//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYGIS.Livelihood
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Station
    {
        public System.Guid Sta_Guid { get; set; }
        public Nullable<int> Sta_Id { get; set; }
        public string Sta_Name { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Sta_Geo { get; set; }
    }
}
