//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYGIS.Livelihood
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Traffic
    {
        public System.Guid T_Guid { get; set; }
        public string T_Type { get; set; }
        public string T_Name { get; set; }
        public string T_Address { get; set; }
        public string T_QH { get; set; }
        public Nullable<int> T_Number { get; set; }
        public System.Data.Entity.Spatial.DbGeometry T_Geo { get; set; }
        public string T_Introduce { get; set; }
        public Nullable<int> T_PhotoList { get; set; }
    }
}
