//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYGIS.Livelihood
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public System.Guid U_Guid { get; set; }
        public string U_Name { get; set; }
        public string U_Acc { get; set; }
        public string U_Pwd { get; set; }
    }
}
