//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYGIS.Livelihood
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Culture_Community
    {
        public System.Guid C_C_Guid { get; set; }
        public string C_C_Name { get; set; }
        public string C_C_Address { get; set; }
        public string C_C_QH { get; set; }
        public System.Data.Entity.Spatial.DbGeometry C_C_Geo { get; set; }
        public Nullable<System.Guid> C_EduId1 { get; set; }
        public Nullable<System.Guid> C_EduId2 { get; set; }
    }
}
