//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYGIS.Livelihood
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BusLine
    {
        public System.Guid BL_Guid { get; set; }
        public Nullable<int> BL_Id { get; set; }
        public string BL_Name { get; set; }
        public string BL_ShortName { get; set; }
        public Nullable<int> BL_UpStartStationId { get; set; }
        public Nullable<int> BL_UpEndStationId { get; set; }
        public Nullable<int> BL_DownStartStationId { get; set; }
        public Nullable<int> BL_DownEndStationId { get; set; }
        public string BL_UpStartTime { get; set; }
        public string BL_UpEndTime { get; set; }
        public string BL_DownStartTime { get; set; }
        public string BL_DownEndTime { get; set; }
        public string BL_LineType { get; set; }
        public System.Data.Entity.Spatial.DbGeometry BL_Geo { get; set; }
    }
}
